baseURL = "http://localhost:1313/MSQM/"
#baseURL = "https://lcpq.github.io/MSQM/"
canonifyurls  = true
languageCode = "en-us"
DefaultContentLanguage = "en"
theme = "beautifulhugo"
title = "MODEL SYSTEMS IN QUANTUM MECHANICS (11-12 Jan 2024, Toulouse)"
[Params]
  hometitle = "WORKSHOP ON MODEL SYSTEMS IN QUANTUM MECHANICS"
  logo="img/sphericalcow.png"
#  subtitle = ""
[[Params.bigimg]]
  src = "img/banner.png"
  desc = "GDR NBODY"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
 [Author]
   name = "GDR NBODY"
   email = "gdrnbody@lct.jussieu.fr"
   github = "LCPQ"
   twitter = "GDR_NBODY"
   youtube = "@GDRNBODY/featured"

[[menu.main]]
    name = "Home"
    url = ""
    weight = 1

[[menu.main]]
    name = "Program"
    url = "planning"
    weight = 2

 [[menu.main]]
     name="Presentations"
     url = "presentations"
     weight = 3

[[menu.main]]
    name = "Location"
    url = "map"
    weight = 4

[[menu.main]]
    name = "Registration"
    url = "registration"
    weight = 5

[[menu.main]]
    name = "Sponsors"
    url = "sponsors"
    weight = 6

#[[menu.main]]
#    parent="external"
#    name = "CNRS"
#    url = "http://www.cnrs.fr"
#    weight = 2

